Document: kalibro-configurations
Title: Debian kalibro-configurations Manual
Author: <insert document author here>
Abstract: This manual describes what kalibro-configurations is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kalibro-configurations/kalibro-configurations.sgml.gz

Format: postscript
Files: /usr/share/doc/kalibro-configurations/kalibro-configurations.ps.gz

Format: text
Files: /usr/share/doc/kalibro-configurations/kalibro-configurations.text.gz

Format: HTML
Index: /usr/share/doc/kalibro-configurations/html/index.html
Files: /usr/share/doc/kalibro-configurations/html/*.html
