#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'build-essential', '~> 2.2.3'
cookbook 'vim', '~> 1.1.2'
cookbook 'nodejs', '~> 2.4.0'
cookbook 'ruby_rvm', '~> 0.4.9'
cookbook 'rvm', '~> 0.9.2'
cookbook 'postgresql', '~> 3.4.20'
cookbook 'git', '~> 4.2.2'