# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version.
# Don't change unless you know what you're doing!i
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "chef/ubuntu-14.04"

  config.omnibus.chef_version = "11.16"

  # Create a forwarded port mapping which allows access to a specific port
  # Rails server port
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  # MySQL server port
  config.vm.network "forwarded_port", guest: 3306, host: 3308

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Configuration for cooking with chef
  config.vm.provision :chef_solo do |chef|
    # Cooking :)
    chef.cookbooks_path = ["cookbooks", "site-cookbooks"]
    chef.add_recipe "nodejs"
    chef.add_recipe "vim"
    chef.add_recipe "mysql::server"
    chef.add_recipe "mysql::client"
    chef.add_recipe "rvm::system"
    chef.add_recipe "rvm::vagrant"
    chef.add_recipe "build-essential"
    chef.add_recipe "nodejs"

    # Installing Ruby 2.2.2 and Bundle
    # Setting up MySQL
    chef.json = {
      :rvm => {
         'rubies' => ["2.2.2"],
         'default_ruby' => "2.2.2",
         :vagrant => { :system_chef_solo => "/opt/chef/bin/chef-solo" }
      },
      :mysql => {
        server_root_password: 'root'
      }
    }
  end
end
